language: python
python:
  - "3.5"

# command to install dependencies
install:
  - pip install
  
# command to run tests
script: nosetests

# blacklist
branches:
  except:
    - legacy
    - experimental
    - wip

# whitelist
  only:
    - master
    - stable
